# work directory for file server
directory: FileServer
# application host
host: 127.0.0.1
# applicaton port
port: 80
# log directory
log_dir: Logs
# logging level 10-DEBUG, 20-INFO, 30-WARNING, 40-ERROR, 50-CRITICAL
log_level: 10